plant:
    code        : 4025
    latitude    : 42.571145
    longitude   : -83.034768
    market_id   : 7
    shift_days  : 4
    shift_hours : 10
    absence_codes: [
        'BERC',
        'BERE',
        'BERU',
        'BERX',
        'CARE',
        'CARU',
        'FMLA',
        'FMLD',
        'FMLU',
        'HOMD',
        'ILFE',
        'ILFU',
        'IPBE',
        'IPME',
        'IPNU',
        'IPSE',
        'JURE',
        'MISE',
        'MISU',
        'PERU',
        'PPAA',
        'PPAU',
        'TRAG',
        'WTRU']
    exclude_dates: ['2018-01-12',
                    '2018-01-13',
                    '2018-01-19',
                    '2018-01-20',
                    '2018-01-26',
                    '2018-01-27',
                    '2018-02-03',
                    '2018-02-09',
                    '2018-02-10',
                    ['2019-01-02', '2019-01-11'],
                    ['2019-07-15', '2019-07-20'],
                    ['2020-01-01', '2020-01-20'],
                    ['2020-07-20', '2020-07-25']]

base_table:
    start_date     : 2017-01-01
    end_date       :
    use_table      :
    use_table_date :
    write_table    : True

model:
    models           : ['sarimax']
    target           : absences_unplanned
    npreds           : 4
    p_arima          : 1
    d_arima          : 0
    q_arima          : 0
    features         : [
        'actual_hours',
        'lost_hours',
        'absences_unplanned_rolling_median_12',
        'absences_unplanned_rolling_median_20',
        'quarter',
        'month',
        'week',
        'day',
        'day_of_week',
        'day_of_year']
    top_features     : 5
    band_pct         : 0.3
    levels           : ['crew', 'production_line']
    crews            : ['A', 'B', 'C']
    departments      : {'Quality'      : '3200',
                        'Material'     : '3330',
                        'Trades'       : '3460',
                        'Body Shop 1'  : '9110',
                        'Body Shop 2'  : '9112',
                        'Paint Shop 1' : '9130',
                        'Paint Shop 2' : '9132',
                        'Trim'         : '9150',
                        'Chassis'      : '9170',
                        'Final'        : '9171',
                        'Reprocess'    : '9190'}
    production_lines : {'Body Shop 1 FRT FLR ASM / Ladder ASM'                   : ['Body Shop 1',
                            ['01']],
                        'Body Shop 1 UBF & RH BSI / BSO'                         : ['Body Shop 1',
                            ['02']],
                        'Body Shop 1 RH DR BTM & LH BSI / BSO & BODY FMR'        : ['Body Shop 1',
                            ['03']],
                        'Body Shop 1 RH FRT & RR DR ASM / SEG 1 RH DR / BIW FIT' : ['Body Shop 1',
                            ['04']],
                        'Body Shop 1 LH FRT & RR DR ASM / SEG 2 LH DR'           : ['Body Shop 1',
                            ['05']],
                        'Body Shop 1 LH DR BTM & SEG 3 LH FNDR & SEG 4 HD INS'   : ['Body Shop 1',
                            ['06']],
                        'Body Shop 1 SEG 3 RH FNDR & HOOD ASM & SEG 4 HD INST'   : ['Body Shop 1',
                            ['07']],
                        'Body Shop 1 RH Metal Finish / Offline Repair'           : ['Body Shop 1',
                            ['08']],
                        'Body Shop 1 LH Metal Finish / Offline Repair'           : ['Body Shop 1',
                            ['09']],
                        'Body Shop 2 Box Assembly Line'                          : ['Body Shop 2',
                            ['01']],
                        'Body Shop 2 Box Panel Line'                             : ['Body Shop 2',
                            ['02']],
                        'Body Shop 2 Box Metal Finish Off Line Repair'           : ['Body Shop 2',
                            ['03']],
                        'Body Shop 2 TCF Fitters'                                : ['Body Shop 2',
                            ['04']],
                        'Chassis Pre-Frame Flip 1'     : ['Chassis',
                            ['01', '02', '03', '04', '05', '06', '07', '08', '09']],
                        'Chassis Pre-Frame Flip 2'     : ['Chassis',
                            ['15', '16', '17', '18', '19']],
                        'Chassis Pre-Frame Flip 3'     : ['Chassis',
                            ['25', '26', '27', '28']],
                        'Chassis Post-Frame Flip 4'    : ['Chassis',
                            ['30', '31', '32']],
                        'Chassis Post-Frame Flip 5'    : ['Chassis',
                            ['35', '36', '37', '38', '39', '40']],
                        'Chassis Engine Loop'          : ['Chassis',
                            ['45', '46', '47']],
                        'Chassis Engine 1'             : ['Chassis',
                            ['50', '51', '52', '53']],
                        'Chassis Engine 2'             : ['Chassis',
                            ['60', '61', '62', '63']],
                        'Chassis Engine Kit'           : ['Chassis',
                            ['65', '66']],
                        'Final 1'                      : ['Final',
                            ['01', '02', '03', '04', '05', '06', '07']],
                        'Final Mezz'                   : ['Final',
                            ['10']],
                        'Final 2'                      : ['Final',
                            ['11', '12']],
                        'Final 3'                      : ['Final',
                            ['15', '16', '17', '18']],
                        'Final 4'                      : ['Final',
                            ['20', '21', '22']],
                        'Final Flat Top'               : ['Final',
                            ['25', '26', '27', '28']],
                        'Material BIW Cab & Box'       : ['Material',
                            ['01', '02', '03']],
                        'Material West Dock CMA'       : ['Material',
                            ['04']],
                        'Material North Dock CMA'      : ['Material',
                            ['05']],
                        'Material West Bulk Delivery'  : ['Material',
                            ['06']],
                        'Material North Bulk Delivery' : ['Material',
                            ['07']],
                        'Material South Dock 1'        : ['Material',
                            ['08']],
                        'Material South Dock 2'        : ['Material',
                            ['09']],
                        'Material Southwest Delivery'  : ['Material',
                            ['10']],
                        'Material Southeast Delivery'  : ['Material',
                            ['11']],
                        'Material SL Prop'             : ['Material',
                            ['12']],
                        'Material SPD Cell N1'         : ['Material',
                            ['13']],
                        'Material SPD Cell N2'         : ['Material',
                            ['14']],
                        'Material SPD Cell West'       : ['Material',
                            ['15']],
                        'Material SPD Cell South W'    : ['Material',
                            ['16']],
                        'Material SPD Cell South N'    : ['Material',
                            ['17']],
                        'Paint Shop 1 ECOAT Tooling / ECOAT Sanding'           : ['Paint Shop 1',
                            ['01']],
                        'Paint Shop 1 Plugs and Patches / BOM'                 : ['Paint Shop 1',
                            ['02']],
                        'Paint Shop 1 Sealer (North)'                          : ['Paint Shop 1',
                            ['03', '04']],
                        'Paint Shop 1 Sealer (South)'                          : ['Paint Shop 1',
                            ['05', '06']],
                        'Paint Shop 1 UBC Masking and DeMasking North'         : ['Paint Shop 1',
                            ['07']],
                        'Paint Shop 1 UBC Masking and DeMasking South'         : ['Paint Shop 1',
                            ['08']],
                        'Paint Shop 1 Powder Color Booth Left Side'            : ['Paint Shop 1',
                            ['09']],
                        'Paint Shop 1 Powder Color Booth Right Side'           : ['Paint Shop 1',
                            ['10']],
                        'Paint Shop 1 TU-TONE'                                 : ['Paint Shop 1',
                            ['11']],
                        'Paint Shop 1 Finesse Left Side'                       : ['Paint Shop 1',
                            ['12']],
                        'Paint Shop 1 Finesse Right Side'                      : ['Paint Shop 1',
                            ['13']],
                        'Paint Shop 1 Heavy Sand Booth & Panel Exchange Left'  : ['Paint Shop 1',
                            ['14']],
                        'Paint Shop 1 Heavy Sand Booth & Panel Exchange Right' : ['Paint Shop 1',
                            ['15']],
                        'Paint Shop 2 Tool Removal'                            : ['Paint Shop 2',
                            ['01']],
                        'Paint Shop 2 Sealer'                                  : ['Paint Shop 2',
                            ['02']],
                        'Paint Shop 2 Color Prep'                              : ['Paint Shop 2',
                            ['03']],
                        'Paint Shop 2 TU-TONE Masking'                         : ['Paint Shop 2',
                            ['04']],
                        'Paint Shop 2 Finesse'                                 : ['Paint Shop 2',
                            ['05']],
                        'Paint Shop 2 Heavy Sanding'                           : ['Paint Shop 2',
                            ['06']],
                        'Quality QVS'                   : ['Quality',
                            ['01']],
                        'Quality Torque'                : ['Quality',
                            ['02']],
                        'Quality Cert'                  : ['Quality',
                            ['03']],
                        'Quality QAC'                   : ['Quality',
                            ['04']],
                        'Quality BIW Weld'              : ['Quality',
                            ['05']],
                        'Quality Paint Pelt'            : ['Quality',
                            ['06']],
                        'Quality Incoming'              : ['Quality',
                            ['07']],
                        'Quality QVS Assembly'          : ['Quality',
                            ['12']],
                        'Reprocess Alignment & Rolls'   : ['Reprocess',
                            ['01']],
                        'Reprocess Operations'          : ['Reprocess',
                            ['04']],
                        'Trades Body Shop North (CAB)'  : ['Trades',
                            ['01']],
                        'Trades Body Shop South (BOX)'  : ['Trades',
                            ['02']],
                        'Trades Assembly'               : ['Trades',
                            ['03']],
                        'Trades Paint Shop North (CAB)' : ['Trades',
                            ['06']],
                        'Trades Paint Shop South (BOX)' : ['Trades',
                            ['07']],
                        'Trades MLM Jitney Repair'      : ['Trades',
                            ['30']],
                        'Trim Pre-Trim'                 : ['Trim',
                            ['01', '02', '03', '04', '05', '06']],
                        'Trim Rotating Carrier'         : ['Trim',
                            ['10', '11', '12', '13']],
                        'Trim 3'                        : ['Trim',
                            ['20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']],
                        'Trim 4'                        : ['Trim',
                            ['35', '36', '37', '38', '39', '40', '41']],
                        'Trim 5'                        : ['Trim',
                            ['45', '46', '47', '48', '49', '50', '51']],
                        'Trim 6'                        : ['Trim',
                            ['55', '56', '57', '58', '59', '60', '61']],
                        'Trim Door Line 1'              : ['Trim',
                            ['65', '66', '67', '68', '69', '70']],
                        'Trim Door Line 2'              : ['Trim',
                            ['75', '76', '77', '78', '79']],
                        'Trim Box Line'                 : ['Trim',
                            ['85', '86', '87', '88', '89', '90']]}
    inactive_production_lines : {}
    write_table : True
    use_peaks   : False
    peak_table  : abs_ad_median_replace_tbl_20190917
 